# HlifeApi pipeline(windows下的docker desktop) 
kind: pipeline
type: exec
name: hlifeapi

platform:
  os: windows       # 告诉 Drone 这是 Windows 宿主机
  arch: amd64

trigger:
  branch:
    - master
  event:
    - push

steps:
- name: 构建
  commands:
    - docker compose -f .\HlifeApi\docker-compose.yml build   # Windows 路径反斜杠

- name: 部署
  commands:
    - docker compose -f .\HlifeApi\docker-compose.yml down
    - docker compose -f .\HlifeApi\docker-compose.yml up -d
 




