# HlifeApi pipeline(windows下的docker desktop) 
kind: pipeline
type: exec
name: hlifeapi

platform:
  os: windows 
  arch: amd64

trigger:
  branch:
    - master
  event:
    - push

steps:
- name: 设置代理 
  commands: 
    - git config --global http.proxy socks5://192.168.50.3:1070
    - git config --global https.proxy socks5://192.168.50.3:1070
    - git config --global --get http.proxy
    - git config --global --get https.proxy

- name: 构建
  commands:
    - docker compose -f .\HlifeApi\docker-compose.yml build   # Windows 路径反斜杠

- name: 部署
  commands:
    - docker compose -f .\HlifeApi\docker-compose.yml down
    - docker compose -f .\HlifeApi\docker-compose.yml up -d