# HlifeApi pipeline(windows下的docker desktop)
---
kind: pipeline
type: docker
name: hlifeapi
trigger:
  branch:
    - main
  event:
    - push

steps:
- name: 构建
  image: docker:20.10-cli   
  volumes:
    - name: dockersock
      path: /var/run/docker.sock  
  commands:
    - docker compose -f ./HlifeApi/docker-compose.yml build 

- name: 部署
  image: docker:20.10-cli  
  volumes:
    - name: dockersock
      path: /var/run/docker.sock  
  commands: 
    - docker compose down 
    - docker compose -f ./HlifeApi/docker-compose.yml up -d
volumes:
- name: dockersock
  host:
    path: //./pipe/docker_engine  # 关键：映射宿主机 Docker 守护进程

